/*
 * Proddx API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package router

import (
	"fmt"
	"net/http"

	"github.com/julienschmidt/httprouter"
)

func New() *httprouter.Router {
	router := httprouter.New()

	router.Handler(http.MethodGet, "/", Logger(Index(), "Index"))

	router.Handler(http.MethodGet, "/companies", Logger(listCompanies(), "ListCompanies"))
	router.Handler(http.MethodPost, "/companies", Logger(insertCompany(), "InsertCompany"))
	router.Handler(http.MethodGet, "/companies/:id", Logger(findCompany(), "FindCompany"))
	router.Handler(http.MethodPut, "/companies/:id", Logger(updateCompany(), "UpdateCompany"))
	router.Handler(http.MethodDelete, "/companies/:id", Logger(deleteCompany(), "DeleteCompany"))

	router.Handler(http.MethodGet, "/products", Logger(listProducts(), "ListProducts"))
	router.Handler(http.MethodPost, "/products", Logger(insertProduct(), "InsertProduct"))
	router.Handler(http.MethodGet, "/products/:id", Logger(findProduct(), "FindProduct"))
	router.Handler(http.MethodPut, "/products/:id", Logger(updateProduct(), "UpdateProduct"))
	router.Handler(http.MethodDelete, "/products/:id", Logger(deleteProduct(), "DeleteProduct"))

	router.Handler(http.MethodGet, "/reviews", Logger(listReviews(), "ListReviews"))
	router.Handler(http.MethodPost, "/reviews", Logger(insertReview(), "InsertReview"))
	router.Handler(http.MethodGet, "/reviews/:id", Logger(findReview(), "FindReview"))
	router.Handler(http.MethodPut, "/reviews/:id", Logger(updateReview(), "UpdateReview"))
	router.Handler(http.MethodDelete, "/reviews/:id", Logger(deleteReview(), "DeleteReview"))

	return router
}

func Index() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello World!")
	}
}
