/*
 * Proddx API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Product struct {

	Id string `json:"id,omitempty"`

	CompanyId string `json:"company_id,omitempty"`

	Name string `json:"name,omitempty"`

	FeedbackUrl string `json:"feedback_url,omitempty"`

	Rating float64 `json:"rating,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`
}
