/*
 * Proddx API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Company struct {

	Id string `json:"id,omitempty"`

	UserId string `json:"user_id,omitempty"`

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	Logo string `json:"logo,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`
}
