/*
 * Proddx API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Review struct {

	Id string `json:"id,omitempty"`

	CompanyId string `json:"company_id,omitempty"`

	ProductId string `json:"product_id,omitempty"`

	Comment string `json:"comment,omitempty"`

	Rating float64 `json:"rating,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`
}
