/*
 * Proddx API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"context"
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "api.proddx.com/router"
	"api.proddx.com/storage"
	"github.com/jackc/pgx/v4/pgxpool"
)

func main() {
	log.Printf("Server started")

	ctx := context.Background()

	pool, err := pgxpool.Connect(ctx, "postgres://novi:novi@localhost:5432/proddx_db?sslmode=disable")
	if err != nil {
		log.Fatalf("Failed to connect to database: %s", err.Error())
	}
	defer pool.Close()

	userStore := &storage.UserDatabase{Pool: pool}
	companyStore := &storage.CompanyDatabase{Pool: pool}
	productStore := &storage.ProductDatabase{Pool: pool}
	reviewStore := &storage.ReviewDatabase{Pool: pool}

	router := sw.New(userStore, companyStore, productStore, reviewStore)

	log.Fatal(http.ListenAndServe(":5000", router))
}
